[package]
name = "arc164"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = "0.4.3"
petgraph = "0.6.3"
rug = "1.10"
[profile.release]
lto = true
panic = 'abort'
