[package]
name = "arc067"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = "0.4.3"
petgraph = "0.6.3"
num-bigint = "0.4.4"
num-traits = "0.2"
[profile.release]
lto = true
panic = 'abort'
