[package]
name = "abc271"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = "0.4.3"
itertools = "0.11.0"
petgraph = "0.6.3"
[profile.release]
lto = true
panic = 'abort'
